using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EventRecognizer.Api.Models;

/// <summary>
/// Database entity representing a recognized event.
/// </summary>
public class EventRecord
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Unique event identifier generated from recognition (e.g., "EVT-20250728-ABC123").
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string EventUniqueId { get; set; } = string.Empty;

    /// <summary>
    /// Event title extracted by the LLM.
    /// </summary>
    [Required]
    [MaxLength(300)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Event date and time extracted by the LLM.
    /// </summary>
    public DateTime? EventDate { get; set; }

    /// <summary>
    /// Human-readable date/time description from the LLM (handles cases like "every Thursday").
    /// </summary>
    [MaxLength(500)]
    public string? EventDateDescription { get; set; }

    /// <summary>
    /// Brief summary of the event generated by the LLM.
    /// </summary>
    [Required]
    [MaxLength(2000)]
    public string Summary { get; set; } = string.Empty;

    // Original Instagram post data
    [Required]
    [MaxLength(200)]
    public string Account { get; set; } = string.Empty;

    [Required]
    [MaxLength(100)]
    public string PostId { get; set; } = string.Empty;

    [MaxLength(500)]
    public string Caption { get; set; } = string.Empty;

    public DateTime? PostDatetime { get; set; }

    [MaxLength(500)]
    public string Url { get; set; } = string.Empty;

    [MaxLength(1000)]
    public string? ImageUrl { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
